version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: bchnd
      APP_PORT: 8332
      PROXY_AUTH_ADD: "false"

  bchnd:
    image: zquestz/bitcoin-cash-node:28.0.1
    restart: on-failure
    command: >
      bitcoind
      -datadir=/data
      -rpcuser=bchrpc
      -rpcpassword=changeme
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcport=8332
      -server=1
      -txindex=1
    volumes:
      - ${APP_DATA_DIR}/data/bchnd:/data

  ckpool:
    image: ghcr.io/getumbrel/docker-ckpool-solo:590fb2a
    restart: on-failure
    ports:
      - "3333:3333"
    environment:
      - BTCHOST=bchnd
      - BTCPORT=8332
      - BTCUSER=bchrpc
      - BTCPASS=changeme
    depends_on:
      - bchnd
