version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 80
    networks:
      - default
      - umbrel_main_network

  web:
    image: nginx:1.27-alpine
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/exports/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/exports/app:/usr/share/nginx/html:ro
    networks:
      - default
      - umbrel_main_network
    depends_on:
      - api

  bchnd:
    image: zquestz/bitcoin-cash-node:28.0.1
    restart: on-failure
    stop_grace_period: 15m
    command: >
      bitcoind
      -datadir=/data
      -rpcuser=bchrpc
      -rpcpassword=changeme_rpc
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcport=8332
      -server=1
      -txindex=1
      -addnode=seed.flowee.cash
      -addnode=seeder.criptolayer.net
    volumes:
      - ${APP_DATA_DIR}/data/bchnd:/data

  ckpool:
    image: ghcr.io/getumbrel/docker-ckpool-solo:590fb2a
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "3333:3333/tcp"
    volumes:
      - ${APP_DATA_DIR}/data/ckpool:/data
      - ${APP_DATA_DIR}/scripts/init.sh:/scripts/init.sh:ro
    entrypoint: ["/bin/sh", "/scripts/init.sh"]
    depends_on:
      - bchnd

  api:
    image: ghcr.io/mikeyrock/projectx-api:latest
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data/ckpool:/data
    environment:
      - BCH_RPC_HOST=bchnd
      - BCH_RPC_PORT=8332
      - SETTINGS_FILE=/data/projectx-settings.json
      - LOG_FILE=/data/ckpool.log
    depends_on:
      - bchnd
      - ckpool

networks:
  default:
  umbrel_main_network:
    external: true
    name: umbrel_main_network
